### ISSUE TITLE
HTML is not styling tool but markup language.

### ISSUE THREAD

**Issue by AkihiroTokai** [GenbuHase/genbuhase.github.io#2]
Blog本文での段落分けは `<br>`を連続して使うのではなくSCSSでやったほうがいいのでは。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/br

**Comment by GenbuHase** [comment]
仰る通りですねー。
受験終わったら全部作り直そうって思ってたりするので、まとめてやっちゃいますー！

ありがとうございます🙏

**Comment by GenbuHase** [comment]
@AkihiroTokai 
お世話になっております。

こちらのIssueですが、こちらのコミット(c496f5db9126312f74ac36cb0eff04b4c7ecdf9b)で改善されましたのでお知らせいたします。この度はご指摘いただきありがとうございました！
